# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XR8Wc_B0riwjrhPe0s4SFBbJC6STYtQG
"""

!pip install requests beautifulsoup4 pandas openpyxl

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
from datetime import datetime
from google.colab import files

# ==========================================
# 1. [기능] 실시간 랭킹 뉴스 (Start-up Dashboard)
# ==========================================
def get_ranking_news():
    print("⏳ 오늘의 통합 랭킹 뉴스를 불러옵니다...")
    url = "https://news.naver.com/main/ranking/popularDay.naver"

    # 로봇이 아님을 증명하기 위한 헤더
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36'}

    try:
        response = requests.get(url, headers=headers)
        soup = BeautifulSoup(response.text, 'html.parser')

        news_boxes = soup.select(".rankingnews_box")
        ranking_data = []

        count = 0
        for box in news_boxes:
            try:
                press_name = box.select_one(".rankingnews_name").text
                list_content = box.select(".list_content > a")

                for news in list_content[:1]: # 각 언론사별 1등 기사만
                    title = news.text
                    link = news['href']
                    ranking_data.append([press_name, title, link])
                    count += 1
                if count >= 5: break
            except:
                continue

        return ranking_data
    except Exception as e:
        print(f"랭킹 로딩 에러: {e}")
        return []

# ==========================================
# 2. [핵심 기능] 분야별 뉴스 모아보기 (경제, IT 등)
# ==========================================
def get_category_news(code, category_name):
    print(f"\n📂 '{category_name}' 분야의 주요 뉴스를 가져옵니다...")

    # 네이버 뉴스 섹션 URL
    url = f"https://news.naver.com/section/{code}"

    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36'}

    try:
        response = requests.get(url, headers=headers)
        soup = BeautifulSoup(response.text, 'html.parser')

        # 섹션별 메인 기사 리스트
        articles = soup.select(".sa_text")
        news_data = []

        count = 0
        for article in articles:
            if count >= 10: break # 상위 10개 수집

            try:
                title_tag = article.select_one(".sa_text_title")
                title = title_tag.text.strip()
                link = title_tag['href']

                # 요약문(미리보기) 추출
                desc_tag = article.select_one(".sa_text_lede")
                desc = desc_tag.text.strip() if desc_tag else "내용 미리보기가 없습니다."

                news_data.append({
                    "순위": count + 1,
                    "분류": category_name,
                    "언론사": "네이버뉴스",
                    "제목": title,
                    "요약": desc,
                    "링크": link
                })
                count += 1
            except:
                continue

        # 만약 데이터가 없으면 비상 메시지 출력
        if not news_data:
            print("⚠️ 뉴스 데이터를 찾지 못했습니다. (HTML 구조 변경 가능성)")

        return news_data

    except Exception as e:
        print(f"오류 발생: {e}")
        return []

# ==========================================
# 3. 결과 저장 및 출력 함수
# ==========================================
def save_and_print(data, filename_prefix):
    if not data:
        print("❌ 저장할 데이터가 없습니다.")
        return

    df = pd.DataFrame(data)

    # 화면 출력
    print("\n" + "="*60)
    print(f"📢 수집 결과 (Top {len(df)})")
    print("="*60)

    # 가독성을 위해 제목과 요약 앞부분만 출력
    for i in range(len(df)):
        print(f"[{i+1}] {df.iloc[i]['제목']}")
        print(f"    └─ {df.iloc[i]['요약'][:50]}...")
        print()

    # 파일 저장 (CSV)
    filename = f"{filename_prefix}_{datetime.now().strftime('%H%M')}.csv"

    # 엑셀 한글 깨짐 방지(utf-8-sig)
    df.to_csv(filename, index=False, encoding='utf-8-sig')

    print(f"💾 '{filename}' 파일로 저장 및 다운로드 중...")
    try:
        files.download(filename)
    except:
        print("(로컬 환경에서는 파일이 저장되었습니다.)")

# ==========================================
# 4. 메인 프로그램 (Menu)
# ==========================================
def main():
    print("="*60)
    print("📰  Daily News Curator (분야별 뉴스 큐레이터)")
    print("="*60)

    # [1] 프로그램 시작 시 랭킹 뉴스 보여주기
    rankings = get_ranking_news()
    if rankings:
        print("\n🔥 [실시간 많이 본 뉴스 Top 5]")
        for i, item in enumerate(rankings):
            print(f"{i+1}. {item[1]} ({item[0]})")
    else:
        print("\n(현재 주요 뉴스를 불러올 수 없습니다.)")

    while True:
        print("\n" + "-"*60)
        print("💡 관심 있는 뉴스 분야를 선택하세요:")
        print("1. 💰 경제 (증권, 부동산, 금융)")
        print("2. 📱 IT/과학 (AI, 테크, 모바일)")
        print("3. ⚖️ 사회 (사건사고, 교육, 노동)")
        print("4. 🏛️ 정치 (행정, 국회)")
        print("5. 🌍 세계 (국제 이슈)")
        print("0. ❌ 종료")
        print("-"*60)

        choice = input(">>> 번호 입력: ")

        # 네이버 뉴스 섹션 코드 매핑
        categories = {
            '1': ('101', '경제'),
            '2': ('105', 'IT과학'),
            '3': ('102', '사회'),
            '4': ('100', '정치'),
            '5': ('104', '세계')
        }

        if choice == '0':
            print("👋 프로그램을 종료합니다. 수고하셨습니다!")
            break

        elif choice in categories:
            code, name = categories[choice]
            # 해당 분야 뉴스 크롤링 실행
            data = get_category_news(code, name)
            # 결과 출력 및 저장
            save_and_print(data, f"{name}_뉴스모음")

        else:
            print("⚠️ 잘못된 번호입니다. 다시 입력해주세요.")

if __name__ == "__main__":
    main()